Make rows clickable on resource list
cortezaproject/corteza pull request #1178
Opened 2023-04-27 17:13 UTC by EmmyMay

# The following changes are implemented
TODO: Summary

# Changes in the user interface:
TODO: Add screenshots, recordings or remove this section

# Checklist when submitting a final (!draft) PR
 - [ ] Commits are tidied up, squashed if needed and follow guidelines in CONTRIBUTING.md
 - [ ] Code builds
 - [ ] All existing tests pass
 - [ ] All new critical code is covered by tests
 - [ ] PR is linked to the relevant issue(s)
 - [ ] Rebased with the target branch

2023-05-26 09:15 UTC, Fajfa requested changes
1. Revert editors
2. Add reusable handle delete to listHelpers that takes resource and deletes it
3. Try adding one style to CResourceList that covers actions
4. Remove everything except handle row clicked, clickable and slot definition (delete,permissions)
5. Make sure slot definition permissions are correctly applied

2023-05-26 09:29 UTC, Fajfa commented on client/web/admin/src/components/Apigw/CRouteList.vue
> +        <!-- v-if false? Please take a look at this-->
Up to you, you can keep it or remove it

2023-05-31 12:11 UTC, Fajfa requested changes
1. Remove refs from resource lists
2. Remove unused classes from Lists
3. use filterList when deleting resource
4. Rename handleListDelete to for example `handleItemDelete`
5. Move the additional actions to separate branch for now

2023-06-02 11:51 UTC, Fajfa approved these changes

2023-06-05 15:33 UTC, katrinDY commented
Issue found after QC:
- compose -> module list: can't access related pages and 3 dots

https://github.com/cortezaproject/corteza/assets/85161724/69473e65-1278-4ee7-be0e-d9365811026d

- admin -> integration gwt -> routes: style issue on 3 dots menu open

https://github.com/cortezaproject/corteza/assets/85161724/69b7bbff-5967-478f-b1d4-26bc87009015

2023-06-06 14:49 UTC, katrinDY commented
Final batch 🤞:
- 3 dots/related pages btns not visible from mobile device in all webapps
- wf list and admin wf list: the permission to delete a wf enables/disables the permission to undelete a wf. For example, if I set canDelete to true I'm able to delete and undelete a wf but if I set it to true I cannot delete and undelete a wf

2023-06-07 10:30 UTC, Fajfa approved these changes

2023-06-07 13:30 UTC, Fajfa approved these changes

2023-06-07 13:55 UTC, merged