2023.3.x feature custom css
cortezaproject/corteza pull request #1262
Opened 2023-06-15 10:01 UTC by KinyaElGrande

Ref: https://github.com/cortezaproject/corteza/issues/1224

This PR aims to enhance webapps customization by introducing CSS customization feature at runtime. This feature allows the admin to dynamically customize the CSS styles of the webapps.

To customize CSS for a specific webapp, admins can utilize the following ID selectors to target them:

- `#admin` for the Admin web app
- `#compose` for the Compose web app
- `#discovery` for the Discovery web app
- `#one` for the One web app
- `#privacy`  for the Privacy web app
- `#reporter`  for the Reporter web app
- `#workflow` for the Workflow web app

### Screenshots
![Screenshot 2023-06-15 at 13 00 47](https://github.com/cortezaproject/corteza/assets/32476094/810ccef7-0bfc-4b54-a23e-a50724971eca)

2023-06-16 09:55 UTC, tjerman approved these changes
lgtm; do change the WIP commit to something informative @Fajfa 
Good job lads :ok_hand:

2023-06-16 09:55 UTC, tjerman commented on server/pkg/webapp/serve.go
> +		_, _ = fmt.Fprint(w, service.CurrentSettings.WithDefaults().UI.CustomCSS)
I'd prefer you bring these in via `serveConfig` args and not referencing an exposed thing

2023-06-16 13:03 UTC, Fajfa requested changes

2023-06-16 13:03 UTC, Fajfa commented on client/web/one/public/custom.css
> + color: blueviolet;
Remove this file and my commit please. 
Also if you can spend some time figuring out the sass implementation. Would be really good if we can have it in v1

2023-06-23 11:12 UTC, Fajfa requested changes

2023-06-23 11:12 UTC, Fajfa commented on client/web/admin/src/components/Settings/UI/CUICustomCSS.vue
> +    <c-submit-button
This should be in the footer, like other cards

2023-06-23 11:12 UTC, Fajfa commented on client/web/admin/src/views/UI/Index.vue
> +      :processing="topbar.processing"
you probably meant to use customCSS.processing & submit

2023-06-23 11:12 UTC, Fajfa commented on locale/en/corteza-webapp-admin/ui.settings.yaml
> +     cancel: cancel
you can use saveAndClose from general:label and Cancel can also be added to general:label
So you can remove these two

2023-06-23 11:12 UTC, Fajfa commented on client/web/admin/src/components/Settings/UI/CUICustomCSS.vue
> +        v-model="customCSS"
the v-model should probably be the modalCSSInput no?

2023-06-23 11:12 UTC, Fajfa commented on client/web/admin/src/components/Settings/UI/CUICustomCSS.vue
> +      this.customCSS = this.modalCSSInput
Doesnt this mean that you save it? It shouldn't be saved, so remove this please.
The only time its saved it if you press save and close

2023-06-23 11:12 UTC, Fajfa commented on client/web/admin/src/components/Settings/UI/CUICustomCSS.vue
> +      this.modalCSSInput = undefined
No need for this since its reset on hidden

2023-06-23 11:12 UTC, Fajfa commented on client/web/admin/src/components/Settings/UI/CUICustomCSS.vue
> +      this.modalCSSInput = this.customCSS
this.customCSS = this.modalCSSInput
Since you're saving the one from modal to the one not in the modal

2023-06-23 11:12 UTC, Fajfa commented on client/web/admin/src/components/Settings/UI/CUICustomCSS.vue
> +      this.showEditorModal = !this.showEditorModal
this.showEditorModal = true
Just to avoid edge cases

2023-06-23 13:41 UTC, Fajfa approved these changes

2023-06-27 11:48 UTC, merged