Refine the query for the select all records operation
cortezaproject/corteza pull request #1263
Opened 2023-06-19 13:18 UTC by KinyaElGrande

Refine the query logic used for the select all records feature in the RecordList component, specifically for bulk edit, delete, and undelete operations.

2023-06-19 14:03 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/RecordListBase.vue
> -        let query = ''
let query = this.filter.query

2023-06-19 14:17 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/RecordListBase.vue
> +        :filter-query="filter.query"
rename from filter-query to query

2023-06-19 14:22 UTC, Fajfa commented on client/web/compose/src/components/Public/Record/BulkEdit/index.vue
> +      return this.filterQuery + this.selectedRecords.map(id => `recordID=${id}`).join(' OR ')
return `this.selectedRecords.length ? this.selectedRecords.map(id => `recordID=${id}`).join(' OR ') : this.query`

2023-06-19 14:47 UTC, Fajfa requested changes

2023-06-19 14:47 UTC, Fajfa commented on locale/en/corteza-webapp-compose/notification.yaml
> +  restoreBulkFailed: Could not restore selected records
Fix undeleteFailed aswell please

2023-06-19 14:47 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/RecordListBase.vue
> +              :filter-query="filter.query"
:query="bulkQuery"

bulkQuery is a computed that is used for all bulks

2023-06-19 14:47 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/RecordListBase.vue
>                :selected-records="selectedAllRecords ? [] : selected"
Remove the selected records prop and replace it with query

2023-06-19 14:47 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/RecordListBase.vue
> +        const { moduleID, namespaceID, query } = this.filter
Keep the moduleID and namepsaceID but get query from this.bulkQuery

2023-06-19 14:47 UTC, Fajfa commented on client/web/compose/src/components/Public/Record/BulkEdit/index.vue
> +              @click="handleBulkUpdateSelectedRecords(selectedQuery)"
use query from prop

2023-06-19 14:47 UTC, Fajfa commented on client/web/compose/src/components/Public/Record/BulkEdit/index.vue
> +    filterQuery: {
Rename this to query and remove the selected records prop

2023-06-19 14:47 UTC, Fajfa commented on client/web/compose/src/components/Public/Record/BulkEdit/index.vue
> +    selectedQuery () {
Remove this

2023-06-19 14:47 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/RecordListBase.vue
>          @save="onInlineEdit()"
Add `@close="onInlineEditClose()"`

2023-06-19 14:47 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/RecordListBase.vue
>            .recordBulkDelete({ moduleID, namespaceID, query })
```
    editInlineField (record, field) {
      this.inlineEdit.fields = [field]
      this.inlineEdit.record = record.clone()
      this.inlineEdit.query = `recordID = ${record.recordID}`
    },

    onInlineEditClose () {
      this.inlineEdit.fields = []
      this.inlineEdit.record = {}
      this.inlineEdit.query = ''
    },

    onInlineEdit () {
      this.refresh(true)
      this.onInlineEditClose()
    },
```

2023-06-19 14:47 UTC, Fajfa commented on client/web/compose/src/components/Public/Record/BulkEdit/index.vue
>    watch: {
Replace selectedRecords watcher with query

```
    query: {
      handler (query) {
        if (!this.openOnSelect || !query.length) return

        this.record = new compose.Record(this.module, this.initialRecord)
        this.showModal = true
      },
    },
```

and add `this.$emit('close')` to the end of onModalHide

```
    onModalHide () {
      this.showModal = false

      if (this.openOnSelect) {
        this.fields = []
        this.record = new compose.Record(this.module, {})
      }
      this.$emit('close')
    },
```

2023-06-20 09:55 UTC, Fajfa approved these changes

2023-06-20 13:10 UTC, katrinDY commented
LGTM

2023-06-23 14:11 UTC, merged