Add inline editing to record block
cortezaproject/corteza pull request #1282
Opened 2023-06-27 12:38 UTC by kelanik8

# The following changes are implemented
TODO: Summary

# Changes in the user interface:
TODO: Add screenshots, recordings or remove this section

# Checklist when submitting a final (!draft) PR
 - [ ] Commits are tidied up, squashed if needed and follow guidelines in CONTRIBUTING.md
 - [ ] Code builds
 - [ ] All existing tests pass
 - [ ] All new critical code is covered by tests
 - [ ] PR is linked to the relevant issue(s)
 - [ ] Rebased with the target branch

2023-06-30 09:28 UTC, Fajfa requested changes

2023-06-30 09:28 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/RecordBase.vue
> +.field-label:hover .inline-actions {
It should be displayed when you hover over the field element, not just the label part)

2023-06-30 09:28 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/RecordBase.vue
> +.field-label{
You can do inline styles in template for this (d-flex align-items-center), the gap you dont need since you have ml-1 on the inline action anyway

2023-06-30 09:28 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/RecordBase.vue
> +  width: fit-content;
I dont think you need this

2023-06-30 09:28 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/RecordConfigurator.vue
> +          <b-form-group
This can be in the general settings section, it belongs there.

2023-06-30 09:28 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/RecordConfigurator.vue
> +            :label="$t('record.inlineEdit.enabled')"
The translation is missing here, should be same/similar as the one in the record list

2023-06-30 09:28 UTC, Fajfa commented on locale/en/corteza-webapp-compose/block.yaml
> +  recordLabel: Records
Since you dont need the extra section, you wont need this

2023-07-03 07:51 UTC, Fajfa approved these changes

2023-07-03 14:47 UTC, katrinDY commented
todo: remove the edit btn when we're in page builder

2023-07-05 12:23 UTC, Fajfa commented
Apply the label changes to other field editors that have it and move to QC

2023-07-05 12:24 UTC, Fajfa requested changes
Apply the field editor changes to all field editors that have label.

2023-07-06 10:23 UTC, katrinDY commented
Writing this down so I don't  forget it:
- inline editing is not disabled on my end when I'm in page builder
- field label isn't truncated but split into two or more lines depending on the field length on samsung s20+ ultra
<img width="185" alt="Screenshot 2023-07-06 at 13 14 37" src="https://github.com/cortezaproject/corteza/assets/85161724/c9dd0815-efd9-4efd-bd9c-d0bff98c28d0">

- in inline editing modal, long-label text appears under the delete button
<img width="185" alt="Screenshot 2023-07-06 at 13 17 28" src="https://github.com/cortezaproject/corteza/assets/85161724/96a0566b-b9a0-4f83-b494-79e4e29ebc24">

2023-07-06 12:27 UTC, katrinDY commented
LGTM

2023-07-07 08:09 UTC, Fajfa approved these changes

2023-07-07 13:27 UTC, katrinDY commented
LGTM

2023-07-10 10:38 UTC, merged