Abort ongoing backend request on a record list block when page is switched
cortezaproject/corteza pull request #1321
Opened 2023-07-11 14:12 UTC by kelanik8

# The following changes are implemented
TODO: Summary

# Changes in the user interface:
TODO: Add screenshots, recordings or remove this section

# Checklist when submitting a final (!draft) PR
 - [ ] Commits are tidied up, squashed if needed and follow guidelines in CONTRIBUTING.md
 - [ ] Code builds
 - [ ] All existing tests pass
 - [ ] All new critical code is covered by tests
 - [ ] PR is linked to the relevant issue(s)
 - [ ] Rebased with the target branch

2023-07-18 10:03 UTC, Fajfa requested changes
Change the trigger of when that happens (beforeDestroy), which should be good.

2023-07-20 15:20 UTC, Fajfa commented
It works great, i think if you can pinpoint a few other requests that would benefit from this
Maybe some record loading, page loading in builder, maybe the chart reporter endpoint.
If you can cover the important(ones who take the most time) until the next release that would be great for performance

2023-07-26 12:41 UTC, Fajfa requested changes
This is a good start, for page blocks. There are still other places, for example views and module fields that would most likely benefit from this, aswell as initial namespace loading.

2023-08-03 09:37 UTC, katrinDY commented
LGTM except for one minor issue:
![4](https://github.com/cortezaproject/corteza/assets/85161724/e879a394-3f9b-483b-bf75-1519bb907989)
<img width="541" alt="Screenshot 2023-08-03 at 12 31 32" src="https://github.com/cortezaproject/corteza/assets/85161724/6fb1015e-3dde-4be1-b858-db898c8db796">

2023-08-07 13:16 UTC, katrinDY commented on client/web/compose/src/components/PageBlocks/AutomationBase.vue
> +    },
Let's add a line between the methods for better readability

2023-08-09 07:33 UTC, tjerman requested changes
I have two comments regarding this.
Here is the TL;DR but do read that wall of text I've prepared for you.

**TL;DR**
You're using a deprecated mechanism which could cause extra work later down the line (we'll probably eventually have to change it).
You're also giving Vue components a bunch of extra low-level knowledge since they have to tell the API client how to cancel and when; the how should be handled by the API client.

As things are, I'm fine with this staying as is, but we should seriously consider what I've thrown together in a later patch release.

I'll send this off as request changes; it's then up to you to decide what you'll do.
**EOF**


## The mechanism you've opted to use is deprecated

From the [axios docs](https://axios-http.com/docs/cancellation), it's noted down that the `cancelToken` mechanism is deprecated.
Was there a specific reason you opted in to use the `cancelToken` vs. `signal` -- usage seems fairly similar to me and it'd fit into how you've designed your code just as well?

![image](https://github.com/cortezaproject/corteza/assets/12545711/6cf6b47e-8051-4562-9baa-1b158afe2b41)

If possible, let's try to avoid deprecated features as much as possible to reduce tech dept as much as possible.

## The integration introduces low-level complexity to the Vue component

Currently, your flow looks like this:

1. Component pings the API client and passes down some cancel bits (that token).
2. The API client makes the API request.
3. Component optionally cancels the API request directly via that mechanism.

TL;DR: your vue component asks the API client to get something as well as tells it how to abort that request.

Overall, this just adds more low-level complexity to the Vue component which, in reality, should be handled by the API client.

This works fine but I'd see a few issues:

1. You're forcing vue components to know what mechanism you're using. Especially now, when we're using a deprecated thing, we'll need to change all of them (if/when we decide to change it). 
2. You're coupling it to Axios which would cause problems if we decide to switch what we use for HTTP (unlikely but still).

TL;DR: your vue component asks the API client to get something; the API client gives us a promise as well as a way to interact with the request (cancel it).

### Possible change

#### Change the API client to provide a `cancel` closure along with the promise

```ts
async recordList (a: KV, extra: AxiosRequestConfig = {}): { response: Promise<KV>, cancel: function() } {...}
```

The `recordList` function in the API client would firstly prepare something to cancel that specific request, and then the cancel closure would invoke the cancelation.

#### Change the vue component to properly handle the new response format (the promise, closure combo)

To cancel requests from the vue component, you'd simply invoke the `cancel` closure; if we need to identify them, we can use some hashmap to index them.

### Problems with the alternate approach

1. If you change the API client function definition, you'll need to update all invocations.
This can be bypassed by either changing the function definition which is backwards-compatible, or by defining a new function (for example `recordListCancellable` which would leave the original function (`recordList`) intact.

2023-08-09 07:33 UTC, tjerman commented on client/web/compose/src/components/PageBlocks/RecordListBase.vue
I think we should also cancel requests for the record list before we do any additional requests (such as changing filters, sorting, ...). Not cancelling old requests would cause issues such as seeing data from the previous request instead of the new request.

2023-08-21 12:03 UTC, merged