Align field value and title horizontally
cortezaproject/corteza pull request #1339
Opened 2023-07-17 14:33 UTC by kelanik8

# The following changes are implemented
TODO: Summary

# Changes in the user interface:
TODO: Add screenshots, recordings or remove this section

# Checklist when submitting a final (!draft) PR
 - [ ] Commits are tidied up, squashed if needed and follow guidelines in CONTRIBUTING.md
 - [ ] Code builds
 - [ ] All existing tests pass
 - [ ] All new critical code is covered by tests
 - [ ] PR is linked to the relevant issue(s)
 - [ ] Rebased with the target branch

2023-07-20 14:41 UTC, Fajfa requested changes
Make it configurable, (on record block)

2023-07-26 11:50 UTC, Fajfa requested changes

2023-07-26 11:50 UTC, Fajfa commented on locale/en/corteza-webapp-compose/block.yaml
> +  alignFieldsHorizontally: Align fields horizontally
Rename this to `Horizontal form layout`

2023-07-26 11:50 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/RecordEditor.vue
>              v-if="isFieldEditable(field)"
If this is false then the form group is no longer inline

2023-07-26 11:50 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/RecordBase.vue
> +        :label-cols-lg="options.horizontalFieldLayoutEnabled && '4'"
You can replace lines 20,21,22 with
```
        :label-cols-md="options.horizontalFieldLayoutEnabled && '5'"
        :label-cols-xl="options.horizontalFieldLayoutEnabled && '4'"
        :content-cols-md="options.horizontalFieldLayoutEnabled && '7'"
        :content-cols-xl="options.horizontalFieldLayoutEnabled && '8'"
```

Same for the module field editors

2023-07-26 11:50 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/RecordBase.vue
>      <!-- Modal for inline editing -->
Add this class in the non scoped section to fix the alignment issues

```
.field-container {
  legend {
    padding-top: 0;
    padding-bottom: 0;
  }
}
```

2023-07-26 11:50 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/RecordEditor.vue
>              :field="field"
Add this class in the non scoped section to fix the alignment issues

```
.field {
  legend {
    padding-top: 0;
    padding-bottom: 0;
  }
}
```

2023-07-26 11:50 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/RecordConfigurator.vue
>              />
Remove the md="6" in on line 14 of this file, it looks a bit better that way

2023-07-26 11:50 UTC, Fajfa commented on client/web/compose/src/components/ModuleFields/Editor/Bool.vue
> +      v-if="field.options.switch || options.horizontalFieldLayoutEnabled"
You dont need the extra check since the only thing that matters is the first condition

2023-07-26 11:50 UTC, Fajfa commented on client/web/compose/src/components/ModuleFields/Editor/Bool.vue
> +        v-if="!field.options.switch && !options.horizontalFieldLayoutEnabled"
You dont need the extra check since the only thing that matters is the first condition

2023-07-26 11:50 UTC, Fajfa commented on client/web/compose/src/components/ModuleFields/Editor/Bool.vue
> +      v-if="!field.options.switch && !options.horizontalFieldLayoutEnabled"
You dont need the extra check since the only thing that matters is the first condition

2023-07-26 11:50 UTC, Fajfa commented on client/web/compose/src/components/ModuleFields/Editor/Bool.vue
> +          class="d-inline-block text-truncate mw-100 py-1"
Transform this py-1 into pb-1 to fix alignment

2023-07-27 11:04 UTC, Fajfa requested changes

2023-07-27 11:04 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/RecordEditor.vue
> +              <label
This section should be same as the record base implementation of the viewers

2023-07-27 11:04 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/RecordEditor.vue
> +            :label-cols-md="block.options.horizontalFieldLayoutEnabled && '5'"
You're gonna probably need a v-else

2023-07-27 11:04 UTC, Fajfa commented on client/web/compose/src/components/ModuleFields/Editor/base.vue
> +    horizontalLayout: {
Just `horizontal` please, also add it for everywhere you use the horizontal value(record base/editor)

2023-07-27 11:04 UTC, Fajfa commented on client/web/compose/src/components/ModuleFields/Editor/base.vue
> +      default: () => false,
The default can be just `default: false`

2023-07-27 11:04 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/RecordEditor.vue
> +            class="mb-3 px-3"
These classes are already applied in the parent element, so remove them please

2023-07-27 11:04 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/RecordEditor.vue
>              class="field"
You're gonna need to move this class to the v-for element if you want the alignment to be resolved

2023-07-27 11:04 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/RecordBase.vue
> +        class="mb-3 px-3"
This class should be conditional like the one below so you should remove it from this line
`:class="{ 'field-container mb-3 px-3': canDisplay(field) }"`

2023-07-27 11:04 UTC, Fajfa commented on client/web/compose/src/components/ModuleFields/Editor/String.vue
> +          class="d-inline-block text-truncate mw-100 py-1"
Add `:class="{ 'text-wrap': horizontal }"`

2023-08-02 07:45 UTC, tjerman approved these changes
Appart from that one comment, lgtm :+1:

2023-08-02 07:45 UTC, tjerman commented on client/web/compose/src/components/ModuleFields/Editor/Bool.vue
> +          :class="{ 'pb-1': !horizontal }"
I might be miss understanding this (I can't run the code at the moment), but I'm not sure I'm a big fan of using padding to achieve a structural change (aligning horizontal vs vertical).

2023-08-07 12:28 UTC, merged