Add changes detection to record editing
cortezaproject/corteza pull request #1367
Opened 2023-08-02 13:59 UTC by kelanik8

# The following changes are implemented
TODO: Summary

# Changes in the user interface:
TODO: Add screenshots, recordings or remove this section

# Checklist when submitting a final (!draft) PR
 - [ ] Commits are tidied up, squashed if needed and follow guidelines in CONTRIBUTING.md
 - [ ] Code builds
 - [ ] All existing tests pass
 - [ ] All new critical code is covered by tests
 - [ ] PR is linked to the relevant issue(s)
 - [ ] Rebased with the target branch

2023-08-23 12:04 UTC, Fajfa reviewed
Regarding this, please test it how it works with modals. 
If all is good, move to QC so it can be confirmed.

2023-08-30 09:58 UTC, Fajfa approved these changes

2023-09-20 10:16 UTC, katrinDY commented
A couple of issues:
- in RL click on the dropdown menu for a record -> edit -> don't make any changes -> go back and the unsaved message is shown
-  in RL click on the dropdown menu for a record -> edit -> don't make any changes -> click on save -> see the toast message `Could not update record: Cannot read properties of undefined (reading 'recordID')`
![1](https://github.com/cortezaproject/corteza/assets/85161724/69dffa4f-fb1d-4e7e-80fe-863087e15d07)
- open a record in modal -> edit a field -> ctr + z the change -> close the modal -> the unsaved message is shown (tried this on text, select and number type of field; the issue should be present for the rest of the field types)
- click on add btn in RL -> add value to a field -> go back -> the unsaved message is *not* shown
- open record in a modal -> click on add -> add value to a field -> close the modal -> the unsaved message is *not* shown

2023-09-25 13:44 UTC, Fajfa requested changes
Would it make sense to keep using the .clone(), but adjusting it on the class
So we can always use clone, similar to how you do it with other change detection

2023-09-26 08:13 UTC, Fajfa approved these changes

2023-10-20 13:30 UTC, katrinDY commented
One last thing and we should be good to go:
![1](https://github.com/cortezaproject/corteza/assets/85161724/a187ee04-d8d9-40cb-89a5-903a54f58f74)

2023-10-23 14:43 UTC, Fajfa approved these changes

2023-10-24 07:24 UTC, katrinDY commented
The issue is still present

2023-10-25 08:28 UTC, Fajfa approved these changes

2023-10-25 12:59 UTC, Fajfa approved these changes

2023-10-26 07:21 UTC, katrinDY commented
- happens only in CRM and Case management
![1](https://github.com/cortezaproject/corteza/assets/85161724/87a951b5-7cd3-4b2d-b2f1-084e25eb66fb)

2023-10-26 12:52 UTC, katrinDY commented on client/web/compose/src/views/Public/Pages/Records/View.vue
> +        console.log('recordStateChange', recordStateChange)
Do you need this? If not, please, remove

2023-10-27 13:35 UTC, Fajfa approved these changes

2023-10-30 10:17 UTC, merged