Fix page builder save on close route to route back to the view page
cortezaproject/corteza pull request #1387
Opened 2023-08-23 12:41 UTC by kelanik8

# The following changes are implemented
TODO: Summary

# Changes in the user interface:
TODO: Add screenshots, recordings or remove this section

# Checklist when submitting a final (!draft) PR
 - [ ] Commits are tidied up, squashed if needed and follow guidelines in CONTRIBUTING.md
 - [ ] Code builds
 - [ ] All existing tests pass
 - [ ] All new critical code is covered by tests
 - [ ] PR is linked to the relevant issue(s)
 - [ ] Rebased with the target branch

2023-08-30 09:53 UTC, Fajfa requested changes

2023-08-30 09:53 UTC, Fajfa commented on client/web/compose/src/store/ui.js
> +        if (state.previousPage && state.previousPage.name) {
I would move this to the setPrevious page, so you dont need to check in the getter

2023-08-30 13:29 UTC, Fajfa approved these changes

2023-08-31 15:01 UTC, katrinDY commented
I'm not redirected to the prev page after:

- opening a record in a new tab -> page builder -> save and close
- module list -> related pages -> click on edit record page/edit record list page ->  save and close
- module edit -> related pages -> click on edit record page/edit record list page of any page -> save and close
- page tree -> page builder of any page -> save and close

2023-09-04 09:25 UTC, katrinDY commented
One more case to resolve:
- public pages -> Home -> edit page -> save and close -> I'm redirected to page tree instead of Home in public view

2023-09-05 07:45 UTC, katrinDY commented
I found a strange edge case for modules and charts:
- chart list -> select any chart type -> add chart name -> save -> click on back and you're redirected to create view -> click on back again and you're redirected to edit view of the new chart -> click on back again and you're redirected to edit view of the new chart => the cycle never ends
- it's the same when creating a module

_the issue isn't present when creating a ns, page or reccord_

2023-09-07 07:34 UTC, merged