Add improvement to tabbed page block configuration
cortezaproject/corteza pull request #1416
Opened 2023-08-31 23:28 UTC by kelanik8

# The following changes are implemented
TODO: Summary

# Changes in the user interface:
TODO: Add screenshots, recordings or remove this section

# Checklist when submitting a final (!draft) PR
 - [ ] Commits are tidied up, squashed if needed and follow guidelines in CONTRIBUTING.md
 - [ ] Code builds
 - [ ] All existing tests pass
 - [ ] All new critical code is covered by tests
 - [ ] PR is linked to the relevant issue(s)
 - [ ] Rebased with the target branch

2023-09-01 12:36 UTC, Fajfa requested changes

2023-09-01 12:36 UTC, Fajfa commented on client/web/compose/src/views/Admin/Pages/Builder.vue
> +            @edit-tab-item-block="(index) => editBlock(index)"
@edit-block="editBlock"

2023-09-01 12:36 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/TabsBase.vue
> +.tab-menu-item-tool {
Try to use only bootstrap except for text color when pills and active

2023-09-01 12:36 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/TabsBase.vue
> +            <b-button
Use input confirm like toolbox does

2023-09-04 10:43 UTC, Fajfa requested changes

2023-09-04 10:43 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/TabsBase.vue
> +              @click="onTabMenuEditItemClick(tab)"
can we call This editTabbedBlock?

2023-09-04 10:43 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/TabsBase.vue
> +              @confirmed="onTabMenuDeleteItemClick(index)"
Similar for this, deleteTab

2023-09-05 08:28 UTC, Fajfa requested changes

2023-09-05 08:28 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/TabsBase.vue
> +              class="edit-block-btn"
Just to keep it simple, you can do `text-primary border-0 edit-block-btn`
And just overwrite the color in the custom class

```
.tabs-base-block-container .nav-pills {
  &.active .edit-block-btn {
    color: $white !important;
  }
}
```

2023-09-05 11:06 UTC, Fajfa approved these changes

2023-10-06 12:23 UTC, katrinDY commented
- after clicking on the edit button for a RL, the triangle icon signaling that a change was made isn't shown but the unsaved changes message is triggered if I try to leave the page without saving my changes
![3](https://github.com/cortezaproject/corteza/assets/85161724/3eea1bd8-02a7-4697-a29f-217e0ef827ac)
- after clicking on the delete button for a RL, the triangle icon signaling isn't shown annd if I try to leave the page, the unsaved changes message is*not* triggered
![4](https://github.com/cortezaproject/corteza/assets/85161724/f843d425-07ca-448c-bfa7-24c43ca39c7f)

2023-10-16 12:01 UTC, Fajfa requested changes

2023-10-16 12:01 UTC, Fajfa commented on client/web/compose/src/views/Admin/Pages/Builder.vue
> +
Not sure why you have to loop through them, you have the index and the tabIndex, so that's all you need to splice it

2023-10-16 12:01 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/TabsBase.vue
> +              :title="$t('tooltip.unsavedChanges')"
Translation is missing here

2023-10-16 12:01 UTC, Fajfa commented on client/web/compose/src/views/Admin/Pages/Builder.vue
> +        this.blocks.forEach((block) => {
You dont need to do this, you can just add the parent block when you delete a tab.

2023-10-17 11:57 UTC, Fajfa approved these changes

2023-10-20 14:37 UTC, katrinDY commented
Issue:
- when viewing a page in the pubic view or clicking on edit btn next to RL title in tabs pb
<img width="621" alt="Screenshot 2023-10-20 at 17 26 46" src="https://github.com/cortezaproject/corteza/assets/85161724/048a3bbc-b2e9-4f86-83fc-f20f4a43622e">

2023-10-23 14:44 UTC, Fajfa approved these changes

2023-10-24 12:22 UTC, merged