Add back navigation feture on record modal
cortezaproject/corteza pull request #1448
Opened 2023-09-18 14:15 UTC by kelanik8

# The following changes are implemented
TODO: Summary

# Changes in the user interface:
TODO: Add screenshots, recordings or remove this section

# Checklist when submitting a final (!draft) PR
 - [ ] Commits are tidied up, squashed if needed and follow guidelines in CONTRIBUTING.md
 - [ ] Code builds
 - [ ] All existing tests pass
 - [ ] All new critical code is covered by tests
 - [ ] PR is linked to the relevant issue(s)
 - [ ] Rebased with the target branch

2023-09-19 11:38 UTC, Fajfa requested changes

2023-09-19 11:38 UTC, Fajfa commented on client/web/compose/src/views/Public/Pages/Records/View.vue
> +        const { recordID, recordPageID } = this.modalPreviousPages.slice(-1)[0] || {}
you should use same mechanism as the lines below(popPreviousPages)

2023-09-19 11:38 UTC, Fajfa commented on client/web/compose/src/views/Public/Pages/Records/View.vue
> +          this.$emit('on-modal-back', { recordID, recordPageID, pushModalPreviousPage: false })
I would always emit this, if its undefined that means it should be closed (and handled in the module)

2023-09-19 11:38 UTC, Fajfa commented on client/web/compose/src/components/Public/Record/Modal.vue
> +        this.popModalPreviousPage()
As mentioned below, this should be popped in the view/Record.
All the modal does is process the event. Similar to how handle-record-redirect works

2023-09-19 11:57 UTC, Fajfa commented on client/web/compose/src/components/Common/RecordToolbar.vue
> +            :icon="['fas', 'chevron-left']"
If modal has back then show back otherwise show close

2023-09-20 13:56 UTC, Fajfa requested changes

2023-09-20 13:56 UTC, Fajfa commented on client/web/compose/src/views/Public/Pages/Records/View.vue
> +      return this.previousPages.length > 0 || this.modalPreviousPages.length > 0
If its in module then one is useful if no the other is, this way you can have false positives.

2023-10-06 11:52 UTC, katrinDY commented
- this behaves a bit awkwardly. Maybe replace the back button with close or remove it, since, in this case, there's no 'going back' because the modal should be closed. I think we should provide the back option only if there's a previous view to go to. Discuss with Joźe, please
![1](https://github.com/cortezaproject/corteza/assets/85161724/9e20a2bf-635d-498e-9f74-1469758937fc)

- open a record in a modal -> click on edit -> click on back btn -> I'm redirected to the prev view but the modal is closed
![2](https://github.com/cortezaproject/corteza/assets/85161724/dc405780-6375-44c3-b46a-94c2640ddae2)

2023-10-16 12:53 UTC, Fajfa approved these changes
Great job, if all works as it should looks good to me.

2023-10-24 12:26 UTC, merged