Replace all title attributes with actual boostrap tooltip functionality
cortezaproject/corteza pull request #1533
Opened 2023-11-21 16:52 UTC by kelanik8

# The following changes are implemented
TODO: Summary

# Changes in the user interface:
TODO: Add screenshots, recordings or remove this section

# Checklist when submitting a final (!draft) PR
 - [ ] Commits are tidied up, squashed if needed and follow guidelines in CONTRIBUTING.md
 - [ ] Code builds
 - [ ] All existing tests pass
 - [ ] All new critical code is covered by tests
 - [ ] PR is linked to the relevant issue(s)
 - [ ] Rebased with the target branch

2023-11-22 11:34 UTC, Fajfa requested changes

2023-11-22 11:34 UTC, Fajfa commented on client/web/compose/src/components/ModuleFields/Configurator/Geometry.vue
> +            v-b-tooltip.hover="{ title: $t('tooltip.goToCurrentLocation'), container: '#body' }"
I suggest you skip this and do it in the other issue PR, to avoid conflicts. Up to you tho

2023-11-22 11:34 UTC, Fajfa commented on client/web/compose/src/components/ModuleFields/Editor/Geometry.vue
> +          v-b-tooltip.hover="{ title: label, container: '#body' }"
Same here, i would do it on the map issue instead to avoid conflicts and possible problems with that

2023-11-22 11:34 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/GeometryBase.vue
> +            v-b-tooltip.hover="{ title: $t('geometry.tooltip.goToCurrentLocation'), container: '#body' }"
Same here (regarding conflicts)

2023-11-22 11:34 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/GeometryConfigurator/Configurator.vue
> +            v-b-tooltip.hover="{ title: $t('geometry.tooltip.goToCurrentLocation'), container: '#body' }"
Same here (regarding conflicts)

2023-11-24 14:46 UTC, katrinDY commented
Please, discuss everything with Jože before starting to work on it. Sorry for the long comment

A couple of issues:
- prev and next btn in recs
![1](https://github.com/cortezaproject/corteza/assets/85161724/7253c60d-496a-41cd-80cb-f770fff594c9)

- tooltips in sidebar compose
![3](https://github.com/cortezaproject/corteza/assets/85161724/248a4625-816f-41ac-b794-8e195f221ae8)

A couple of suggestions:
- do we need a toolbar that says the same thing as the permission rule?
<img width="358" alt="Screenshot 2023-11-24 at 15 27 36" src="https://github.com/cortezaproject/corteza/assets/85161724/82bf201a-de08-4e56-8388-29a927985eae">

- module field value translations: maybe change it to `Field translation` singular since it's pointing to a specific field
<img width="797" alt="Screenshot 2023-11-24 at 15 31 22" src="https://github.com/cortezaproject/corteza/assets/85161724/9cbd0bab-0680-4d88-a8a9-1aaa516d6e7f">

- same question here: does this make sense?
<img width="261" alt="Screenshot 2023-11-24 at 15 37 19" src="https://github.com/cortezaproject/corteza/assets/85161724/2f346cf6-a723-481b-941c-8ad2a4c37678">

- made add a tooltip for this since non-devs may be confused what's expected of them
<img width="800" alt="Screenshot 2023-11-24 at 15 44 18" src="https://github.com/cortezaproject/corteza/assets/85161724/803de173-4895-44b7-ad09-4bcd27defa91">

- add tooltips to ns edit translations
<img width="1399" alt="Screenshot 2023-11-24 at 15 49 29" src="https://github.com/cortezaproject/corteza/assets/85161724/c2af5c2a-1452-449e-8f3f-dbbc4570fbda">

2023-11-27 11:58 UTC, Fajfa commented
1. If button has only an icon it needs a tooltip
2. If it has text, it should keep using :title

2023-11-28 11:47 UTC, Fajfa requested changes

2023-11-28 11:47 UTC, Fajfa commented on client/web/compose/src/components/Common/Module/FieldExpressions.vue
> +  i18nOptions: {
Does this break anything else tho? Since it wasn't there before

2023-11-28 11:47 UTC, Fajfa commented on client/web/compose/src/components/ModuleFields/Configurator/validation.vue
> +            v-b-tooltip.hover="{ title: $t('validators.error.placeholder'), container: '#body' }"
A bit confused what this translation means, it should be validators.error.tooltip
And should be `Warning text`

2023-11-28 11:47 UTC, Fajfa commented on client/web/compose/src/components/ModuleFields/Editor/Bool.vue
> +          :title="label"
class is always last, not sure why you moved it after it. Same for the others
Guess the linter issue will make this easier

2023-11-28 14:55 UTC, Fajfa approved these changes

2023-11-29 13:39 UTC, katrinDY commented
Two things to address:

1. Missing tooltip for translations btn in gauge chart
<img width="561" alt="Screenshot 2023-11-29 at 15 34 14" src="https://github.com/cortezaproject/corteza/assets/85161724/a4051f37-df38-43c3-99d1-7d83624e9eab">

2. Tooltip position for reminders

https://github.com/cortezaproject/corteza/assets/85161724/a2613de5-b635-45bf-829c-899aa08b76c4

2023-11-30 09:31 UTC, Fajfa requested changes

2023-11-30 09:31 UTC, Fajfa commented on client/web/compose/src/components/Chart/ChartTranslator.vue
> +    v-b-tooltip.hover="{ title: tooltip, container: '#body' }"
Why do it here if you made a prop for c-translator-button?

2023-11-30 09:31 UTC, Fajfa commented on client/web/compose/src/components/Chart/ChartTranslator.vue
> +    tooltip: {
since you do a v-bind to the c-translator-button, you don't need to define the prop

2023-11-30 09:31 UTC, Fajfa commented on client/web/compose/src/components/Chart/Report/RadarChart.vue
> +                  :tooltip="$t('general.translations')"
Instead of doing it on every chart translator, might make sense to just do it in the chart-translator component dirrectly.

2023-11-30 09:31 UTC, Fajfa commented on client/web/compose/src/components/Namespaces/Reminders/List.vue
> +          class="border card shadow-sm my-2 p-1"
Are you sure we can just remove the overflow-auto? Pretty sure it was there for a reason

2023-11-30 12:09 UTC, Fajfa approved these changes

2023-11-30 14:04 UTC, merged