Add support for dark mode in Corteza studio
cortezaproject/corteza pull request #1579
Opened 2023-12-01 17:05 UTC by KinyaElGrande

# Dark mode / Multi-theme Support

Ref: https://github.com/cortezaproject/corteza/issues/1494

Add support for dark-mode theme and multiple themes on corteza studio.

### Additional Changes

1.  Dart-sass installation is checked on server boot up, instead on every request to `/custom.css`
2. FE option to return to default color setting on color-picker modal
3. CSS generation on server boot up.
4. `custom-css` has been provisioned to `custom-css.general` and `branding-sass` to both theme `light` and `dark` themes.

2023-12-11 11:03 UTC, tjerman requested changes
I reviewed it on the code level basis; the structure and stuff, is a bit too much to comprehend. We can take a look at it together at some later point.
So far so good but I'm finding it a bit confusing.

2023-12-11 11:03 UTC, tjerman commented on server/app/boot_levels.go
> +	}
```suggestion
	sassInstalled :=  sass.DartSassTranspiler(log) != nil
```

<3

2023-12-11 11:03 UTC, tjerman commented on server/pkg/provision/stylesheet.go
> +func updateWebappTheme(ctx context.Context, log *zap.Logger, s store.Storer) (err error) {
It's a bit difficult to read this function. Please clean it up and add some notes on what exactly the point of it is.

2023-12-11 11:03 UTC, tjerman commented on server/pkg/provision/stylesheet.go
> +			}
Why does this need to be in a loop? It'd be much easier to clean to have this case out side of the loop

2023-12-11 11:03 UTC, tjerman commented on server/system/rest.yaml
> +      - name: meta
Should the meta also go into the user create endpoint?

2023-12-11 11:03 UTC, tjerman commented on server/system/service/stylesheet.go
> +	sass.DefaultCSS(log, customCSSMap["general"])
These `general` strings are a bit spooky.
Can we have some global constant for these fixed theme names instead?

2023-12-11 11:03 UTC, tjerman commented on server/system/service/stylesheet.go
> +		if str.HashStringSHA256(oldThemesMap[key]) == str.HashStringSHA256(currentThemesMap[key]) {
I'd suggest using a faster algorithm. The only thing that matters here is if the bits match up or not. Generally this needs to be done as fast as possible so things like algorithm security doesn't matter.

2023-12-11 11:03 UTC, tjerman commented on server/system/service/stylesheet.go
> +		transpileSASS(key, complimentaryStylesMap[key], currentThemesMap)
why are all these `transpileSASS` outputs ignored?

2023-12-11 11:03 UTC, tjerman commented on server/system/types/user.go
> +	return p, json.Unmarshal([]byte(ss[0]), p)
```suggestion
	return p, json.Unmarshal([]byte(ss[0]), &p)
```

Shouldn't the Unmarshal fnc get the pointer?

2023-12-11 11:03 UTC, tjerman commented on server/system/service/stylesheet.go
> +		log          = logger.Default()
Should this get the logger from the caller?

2023-12-12 07:43 UTC, KinyaElGrande commented on server/system/service/stylesheet.go
> +		if str.HashStringSHA256(oldThemesMap[key]) == str.HashStringSHA256(currentThemesMap[key]) {
you're right, I've opted for `xxhash`

2023-12-14 10:52 UTC, KinyaElGrande commented on server/system/service/stylesheet.go
> +		transpileSASS(key, complimentaryStylesMap[key], currentThemesMap)
`transpileSASS` is an inner function that doesn't return anything.
https://github.com/cortezaproject/corteza/blob/a9d72137697d2c4a67941d62835db0bb959178b9/server/system/service/stylesheet.go#L100-L106

2023-12-18 09:41 UTC, tjerman commented on server/system/service/stylesheet.go
> +		transpileSASS(key, complimentaryStylesMap[key], currentThemesMap)
ah.. i see

2023-12-19 08:02 UTC, tjerman approved these changes
Looks ok to me; good job man

2023-12-19 08:02 UTC, tjerman commented on server/system/service/stylesheet.go
> +		}
Might be worth splitting this into some functions just to reduce the amount if indentation

2024-01-30 14:49 UTC, merged