Add record list configuration for columns text wrap
cortezaproject/corteza pull request #1663
Opened 2024-01-31 11:50 UTC by kelanik8

# The following changes are implemented
TODO: Summary

# Changes in the user interface:
TODO: Add screenshots, recordings or remove this section

# Checklist when submitting a final (!draft) PR
 - [ ] Commits are tidied up, squashed if needed and follow guidelines in CONTRIBUTING.md
 - [ ] Code builds
 - [ ] All existing tests pass
 - [ ] All new critical code is covered by tests
 - [ ] PR is linked to the relevant issue(s)
 - [ ] Rebased with the target branch

2024-02-01 14:43 UTC, Fajfa requested changes

2024-02-01 14:43 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/RecordListConfigurator.vue
> +                  <span>{{ $t('recordList.record.configureNonWrappingFelids') }}</span>
No need for a span here

2024-02-01 14:43 UTC, Fajfa commented on client/web/compose/src/components/ModuleFields/Viewer/base.vue
> +      const { textStyles } = this.extraOptions
Just in case, add a fallback, so `{ textStyles = {} }`

2024-02-01 14:43 UTC, Fajfa commented on client/web/compose/src/components/ModuleFields/Viewer/String.vue
> +      const { textStyles } = this.extraOptions
Same here, add a fallback just in case

2024-02-02 11:39 UTC, Fajfa approved these changes

2024-03-12 12:59 UTC, Fajfa approved these changes

2024-03-14 11:13 UTC, katrinDY commented
All's good just file names look a bit weird when multi-values are enabled

<img width="1113" alt="Screenshot 2024-03-14 at 13 11 35" src="https://github.com/cortezaproject/corteza/assets/85161724/e5b7f894-d8e1-4aa1-95c8-671ff7a58d14">

2024-03-14 11:18 UTC, katrinDY commented
File names look diff in all records and pages

- all recs
<img width="1113" alt="Screenshot 2024-03-14 at 13 16 13" src="https://github.com/cortezaproject/corteza/assets/85161724/0839c52a-89e5-412e-b8bb-2b6b4adcae3c">

- pages
<img width="1113" alt="Screenshot 2024-03-14 at 13 15 45" src="https://github.com/cortezaproject/corteza/assets/85161724/8af46274-ce41-4462-9c3b-57491aea305c">

2024-04-08 11:12 UTC, merged