Standardize sorting on all c-resource-list-table
cortezaproject/corteza pull request #1669
Opened 2024-02-05 13:02 UTC by kelanik8

# The following changes are implemented
TODO: Summary

# Changes in the user interface:
TODO: Add screenshots, recordings or remove this section

# Checklist when submitting a final (!draft) PR
 - [ ] Commits are tidied up, squashed if needed and follow guidelines in CONTRIBUTING.md
 - [ ] Code builds
 - [ ] All existing tests pass
 - [ ] All new critical code is covered by tests
 - [ ] PR is linked to the relevant issue(s)
 - [ ] Rebased with the target branch

2024-02-06 12:12 UTC, Fajfa requested changes

2024-02-06 12:12 UTC, Fajfa commented on lib/vue/src/components/resourceList/CResourceList.vue
> +                class="mb-1 text-grey"
One really small thing here, if you can remove text-grey, since it doesn't do anything anymore
Same for the one in CRecordList

2024-02-06 12:25 UTC, Fajfa approved these changes

2024-02-06 14:49 UTC, katrinDY commented
Two things:
1. Some fields aren't sorted on the first click - the order doesn't change and on the second, third... click everything's fine

Here's a video of what I mean by that
![1](https://github.com/cortezaproject/corteza/assets/85161724/e0841888-4f3d-45d0-bc39-6b5da324abfe)

Where this happens
- admin: users - fields `name` and `handle`, auth client field `handle`, messaging queue - field `queue`
- compose: module - fields `handle` and `last change`
- privacy: request list - field `status`
- reporter list - field `last change`

2. Sorting doesn't work for sens lvls in admin. Maybe we should disable it here?

2024-02-07 10:51 UTC, Fajfa approved these changes

2024-02-08 09:33 UTC, Fajfa approved these changes

2024-02-08 13:31 UTC, merged