Add options for adding records in RecordList
cortezaproject/corteza pull request #1693
Opened 2024-02-19 16:48 UTC by EmmyMay

# The following changes are implemented
TODO: Summary

# Changes in the user interface:
TODO: Add screenshots, recordings or remove this section

# Checklist when submitting a final (!draft) PR
 - [ ] Commits are tidied up, squashed if needed and follow guidelines in CONTRIBUTING.md
 - [x] Code builds
 - [x] All existing tests pass
 - [x] All new critical code is covered by tests
 - [x] PR is linked to the relevant issue(s)
 - [x] Rebased with the target branch

2024-02-20 12:18 UTC, Fajfa requested changes

2024-02-20 12:18 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/RecordListConfigurator.vue
> +            <b-col
the checkbox should be before the select

2024-02-20 12:18 UTC, Fajfa commented on lib/js/src/compose/types/page-block/record-list.ts
> +       'prefilter',
alignment is off here

2024-02-20 12:18 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/RecordListConfigurator.vue
> +                  :options="recordDisplayOptions"
options should be different, since we're not opening a record here but creating it.

2024-02-20 12:18 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/RecordListConfigurator.vue
> +              v-if="!options.hideAddButton"
We should just show it always actually, probably best.

2024-02-21 15:36 UTC, Fajfa approved these changes

2024-03-18 12:32 UTC, katrinDY commented
A suggestion: maybe renaming `On add record click` to `On '+ Add' record click` or something similar would be more intuitive to the user. Otherwise LGTM

2024-03-20 13:07 UTC, merged