Add visibility condition to page blocks
cortezaproject/corteza pull request #1740
Opened 2024-03-20 18:40 UTC by kelanik8

# The following changes are implemented
TODO: Summary

# Changes in the user interface:
TODO: Add screenshots, recordings or remove this section

# Checklist when submitting a final (!draft) PR
 - [ ] Commits are tidied up, squashed if needed and follow guidelines in CONTRIBUTING.md
 - [ ] Code builds
 - [ ] All existing tests pass
 - [ ] All new critical code is covered by tests
 - [ ] PR is linked to the relevant issue(s)
 - [ ] Rebased with the target branch

2024-03-21 14:39 UTC, Fajfa requested changes
Since logic in page view and record page is quite similar, would it make sense to create a page mixin and put the logic there?

2024-03-21 14:39 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/Configurator.vue
> +          class="pt-2"
Replace this pt-2 with an hr above the h5

2024-03-21 14:39 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/Configurator.vue
> +      return ''
You can use the same docs link as the one in page layouts

2024-03-21 14:39 UTC, Fajfa commented on client/web/compose/src/views/Public/Pages/View.vue
>          if (block) {
I would update this if with the below stuff, since you don't need to set the xywh if you don't push it

2024-03-21 14:39 UTC, Fajfa commented on client/web/compose/src/views/Public/Pages/View.vue
> +          if ((expression && blocksExpressions[blockID]) || !expression) {
You can rewrite this like `!expression || blocksExpressions[blockID]` (same as it is with layouts)

2024-03-21 14:39 UTC, Fajfa commented on client/web/compose/src/views/Public/Pages/Records/View.vue
> +      if (blocks.some(({ meta = {} }) => (meta.visibility || {}).expression)) {
Similar stuff here as the page view comments

2024-03-21 14:48 UTC, Fajfa commented
Step 3: Reactivity in conditions, similar to prefilter

2024-03-27 15:38 UTC, Fajfa approved these changes

2024-03-28 13:37 UTC, katrinDY commented
All works as it should. Maybe an improvement would be to make the modal scrollable instead of having to scroll the whole page

![1](https://github.com/cortezaproject/corteza/assets/85161724/7323ea2a-88b7-4a9e-be17-9f54b483e8b6)

2024-04-02 12:50 UTC, Fajfa approved these changes

2024-04-08 11:18 UTC, merged