Change modal cancel variant
cortezaproject/corteza pull request #1751
Opened 2024-04-03 17:49 UTC by EmmyMay

# The following changes are implemented
TODO: Summary

# Changes in the user interface:
TODO: Add screenshots, recordings or remove this section

# Checklist when submitting a final (!draft) PR
 - [x] Commits are tidied up, squashed if needed and follow guidelines in CONTRIBUTING.md
 - [x] Code builds
 - [x] All existing tests pass
 - [x] All new critical code is covered by tests
 - [x] PR is linked to the relevant issue(s)
 - [x] Rebased with the target branch

2024-04-15 11:54 UTC, Fajfa requested changes
Three things:
1. Search for `cancel-variant="link"` and resolve those since we should be using that anymore.
2. Check all modals by searching for `<b-modal` or `cancel-title` or `@cancel`, and double check again please. There is a couple still that don't have the correct styles.

2024-04-15 11:54 UTC, Fajfa commented on client/web/compose/src/components/Public/Record/BulkEdit/index.vue
> -              class="text-primary"
Previously it wasn't obvious since it was a link, but this button doesn't have the correct margin. You can add gap to the footer

2024-04-18 13:56 UTC, Fajfa approved these changes

2024-04-22 15:11 UTC, katrinDY commented
All looks good just this:

![1](https://github.com/cortezaproject/corteza/assets/85161724/b10191e3-cd90-4cc7-913e-1ab2c1fbec45)

2024-04-30 15:06 UTC, Fajfa approved these changes

2024-05-07 07:34 UTC, katrinDY commented
LGTM

2024-05-14 15:32 UTC, merged