Add options to extended drilldown filtering
cortezaproject/corteza pull request #1793
Opened 2024-05-13 14:02 UTC by kelanik8

# The following changes are implemented
TODO: Summary

# Changes in the user interface:
TODO: Add screenshots, recordings or remove this section

# Checklist when submitting a final (!draft) PR
 - [ ] Commits are tidied up, squashed if needed and follow guidelines in CONTRIBUTING.md
 - [ ] Code builds
 - [ ] All existing tests pass
 - [ ] All new critical code is covered by tests
 - [ ] PR is linked to the relevant issue(s)
 - [ ] Rebased with the target branch

2024-06-24 11:04 UTC, Fajfa requested changes

2024-06-24 11:04 UTC, Fajfa commented on client/web/compose/src/components/Common/RecordListFilter.vue
> +      triggers="click"
Guessing this is temporary?

2024-06-24 11:04 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/RecordListBase.vue
> +          // this.activeFilters = currentFilters.map((f, i) => ({ id: i, name: f.name }))
Is this still needed?

2024-07-05 08:33 UTC, Fajfa requested changes
1. Filtering by undefined value doesn't change UX

2024-07-05 08:33 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/RecordListBase.vue
> +                    {{ formatActiveFilterName(f) }}
Since you have gap 1 you have to have each text in its own element
Otherwise the gap is uneven.

2024-07-05 08:33 UTC, Fajfa commented on locale/en/corteza-webapp-compose/block.yaml
> +    optionsModal:
Is this still needed?

2024-07-05 08:33 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/RecordListBase.vue
> +                      :namespace="namespace"
make the field viewers font bold (class="font-weight-bold and text-primary")

2024-07-05 08:33 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/ChartBase.vue
> +            const { name, label } = chartModule.fields.find(({ name }) => name === field)
fallback here `|| {})` otherwise cant read undefined

2024-07-05 08:33 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/RecordListBase.vue
> +                    @click="removeFilter(groupIdx, filterIndex)"
this doesnt seem aligned

2024-07-08 10:47 UTC, Fajfa requested changes

2024-07-08 10:47 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/RecordListBase.vue
>                      {{ formatActiveFilterName(f) }}
Operators should be same as they are in the dropdown of UI.
Also the LIKE operator is not handled!

2024-07-15 12:28 UTC, Fajfa requested changes

2024-07-15 12:28 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/RecordListBase.vue
> +                    NULL
Should look the same as field values (visually)

2024-07-15 12:28 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/RecordListBase.vue
> +    formatActiveFilterOperator (operator) {
I suggest you move this to the record-filter lib, and turn it into an object instead, its easier to maintain and has less lines of code. Plus the return can be operators[operator]

Also the text should be lower case, for example `Foo is 123`

2024-07-15 12:28 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/RecordListBase.vue
>        this.recordListFilter = this.recordListFilter.concat(filter)
Lets assign only once, unless there is a reason for assigning two times.

2024-07-15 12:28 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/RecordListBase.vue
> +    isBetweenOperator (op) {
Can we move this to record-filter aswell?

2024-07-15 12:28 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/RecordListBase.vue
> +                    <template v-if="isBetweenOperator(f.operator)">
This doesnt seem to work, try it out.

2024-07-15 12:28 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/RecordListBase.vue
> +                      />
This needs to be shown properly, currently, there is no `and` between the values.
Also if one of the values is non existent, then you need to show NULL

2024-07-16 11:53 UTC, Fajfa requested changes
Just translations left.

2024-07-18 09:52 UTC, Fajfa requested changes

2024-07-18 09:52 UTC, Fajfa commented on client/web/compose/src/lib/record-filter.js
> +    return operators[op] || 'IS'
The IS should be lowercase and translated like the rest of them.
Also no need to pass labels to it, just translate the operator when showing it.

2024-07-18 09:52 UTC, Fajfa commented on locale/en/corteza-webapp-compose/block.yaml
> +      nil: "NULL"
you're using `.null` somewhere so you need to change it to that here too

NULL is not really a condition, its more of a value. 
Doesnt matter where you move it honestly, just not under conditions.

2024-07-18 09:52 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/RecordListBase.vue
>                          class="text-primary font-weight-bold"
The AND shouldn't be bold. Only the values/NULL's should be.

2024-07-18 09:52 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/RecordListBase.vue
> +                        {{ $t('recordList.filter.conditions.and') }}
the `AND` should be lowercase if its inside the filter to make it more text like.

2024-07-19 13:26 UTC, Fajfa approved these changes

2024-08-15 11:26 UTC, katrinDY commented
Just this, otherwise LGTM. Nice job!
<img width="1137" alt="Screenshot 2024-08-15 at 14 20 36" src="https://github.com/user-attachments/assets/4c886e85-b2ca-4b04-98b3-7756833b64ba">

2024-09-10 10:14 UTC, merged