2023.9.x feature clone report
cortezaproject/corteza pull request #1805
Opened 2024-05-30 10:25 UTC by EmmyMay

# The following changes are implemented
TODO: Summary

# Changes in the user interface:
TODO: Add screenshots, recordings or remove this section

# Checklist when submitting a final (!draft) PR
 - [x] Commits are tidied up, squashed if needed and follow guidelines in CONTRIBUTING.md
 - [x] Code builds
 - [x] All existing tests pass
 - [x] All new critical code is covered by tests
 - [x] PR is linked to the relevant issue(s)
 - [x] Rebased with the target branch

2024-05-30 10:44 UTC, Fajfa requested changes

2024-05-30 10:44 UTC, Fajfa commented on client/web/reporter/src/components/EditorToolbar.vue
> -        :disabled="deleteDisabled || processingDelete || processing"
You need to keep the processing otherwise the other buttons are clickable when saving is processing.

2024-05-30 10:44 UTC, Fajfa commented on client/web/reporter/src/components/EditorToolbar.vue
>          :processing="processingClone"
The button variant should match the other clone buttons in the system

2024-05-30 10:44 UTC, Fajfa commented on client/web/reporter/src/mixins/report.js
> +      const clonedReport = this.report.clone()
There is no need to clone the report (this causes the list clone to fail)

Just prepare the variables which you get from the report and pass them to the reportCreate

2024-05-30 10:44 UTC, Fajfa commented on client/web/reporter/src/mixins/report.js
> +      const handle = reportHandle ? `${report.handle}_${this.$t('general:cloneSuffix')}` : ''
I know i said to add the clone to the handle, but it just occurred to me that could raise an error if you clone the same report twice (they'll both have same handle)
So its honestly better to not have a handle at all.

2024-05-31 14:03 UTC, katrinDY commented
- After I clone an old report (created a couple of days ago), it's name doesn't appear in report list in left nav
![1](https://github.com/cortezaproject/corteza/assets/85161724/5eb4956d-00d7-4513-95d6-8c1838729a67)

- this isn't the best UI imho. Can't we be redirected to the first/last report instead of repot list?
![2](https://github.com/cortezaproject/corteza/assets/85161724/3950764d-7801-4733-aa4b-6fc6ff26cfc6)

2024-06-13 10:03 UTC, merged