Add support for custom CDN javascripts on webapps
cortezaproject/corteza pull request #1877
Opened 2024-08-08 14:34 UTC by KinyaElGrande

Ref: https://github.com/cortezaproject/corteza/issues/1875

Add support for custom javascript cdns on webapps.

#### Admin UI screenshot:

![Screenshot 2024-08-08 at 17 32 00](https://github.com/user-attachments/assets/d34b4953-946d-4c86-bca1-158d01f767da)

2024-08-12 09:34 UTC, tjerman requested changes
What exactly is the point of this feature?

We're letting users provide arbitrary javascript yet we want them to work with HTML (add appropriate `script` tags and such).
Yet, we're yanking out most of the custom HTML in the preprocessing on server-side.
In server code, you keep stating these are CDN scripts, yet we allow arbitrary code to be added.

I would love to see the following:

* **External script inclusion section**: a section in the UI 100% dedicated for external resource inclusion. A simple list where you add entries and specify all the required parameters (no effort from the user needed).
* **Custom JavaScript section**: a section in the UI 100% dedicated for arbitrary JS which gets injected. I'd love to see an option to add multiple _JS files_ so users can have multiple smaller files instead of a gigantic one.

___

A note on custom JS.

Since Corredor already has client scripts, would it make more sense to utilize/extend that? How much functionality do we want this different JS editor to have? Should this JS section primarily focus on UI & design?

2024-08-12 09:34 UTC, tjerman commented on server/pkg/webapp/serve.go
> +        jsonScripts, err := json.Marshal(scriptsAttrs)
`jsonScripts`?

2024-08-12 09:34 UTC, tjerman commented on server/pkg/webapp/serve.go
> +func traverseScriptsNode(n *html.Node, scripts *[]scriptAttrs) {
Nooo; utilize returns over this pointer stuff; recursive functions can still return correctly

2024-08-19 14:09 UTC, Fajfa requested changes
So in general, rename CDNs to Code Snippets (at least from the user perspective)
Clean up some unneeded code and stylistic details.

2024-08-19 14:09 UTC, Fajfa commented on client/web/admin/src/views/System/Cdns/Index.vue
> +          :success="success"
success and processing should be prefixed with the cdn since that's where you store them

2024-08-19 14:09 UTC, Fajfa commented on client/web/admin/src/views/System/Cdns/Index.vue
> +
Add empty state ("No snippets yet")

2024-08-19 14:09 UTC, Fajfa commented on locale/en/corteza-webapp-admin/navigation.yaml
> +    cdns: CDNs
All user facing things should be called "Code Snippets", we can use cdn internally.

2024-08-19 14:09 UTC, Fajfa commented on client/web/admin/src/components/Settings/System/CDNs/CSystemCdnProviderEditor.vue
> +<template>
I would prefer if you just keep this in the original file. (CDNS/Index)

Also the whole components approach is not needed here since they'll all be the same.

2024-08-19 14:09 UTC, Fajfa commented on client/web/reporter/vue.config-builder.js
> +        '^/cdns-provider.js': {
Sorry to make you change this but i would say code-snippets instead of cdns-provider.
Same for everywhere else.

2024-08-19 14:09 UTC, Fajfa commented on client/web/admin/src/views/System/Cdns/Index.vue
> +        <component
This can be replaced with static html. Just copy the component here

2024-08-19 14:09 UTC, Fajfa commented on client/web/admin/src/views/System/Cdns/Index.vue
> +            Delete
Translation strings. Also the delete button should only be visible for existing code snippets.
It should also be aligned left.

Make sure its an input confirm aswell

2024-08-19 14:09 UTC, Fajfa commented on client/web/admin/src/views/System/Cdns/Index.vue
> +            size="sm"
Remove size="sm" from the buttons, please.

2024-08-19 14:09 UTC, Fajfa commented on client/web/admin/src/views/System/Cdns/Index.vue
> +            OK
Consult other modal footers. In general we have (Delete, Cancel, Save)

2024-08-19 14:09 UTC, Fajfa commented on client/web/admin/src/views/System/Cdns/Index.vue
> +        data: {},
New CDNS should have `<script` as default value, since placeholders are a bit tricky here.

2024-08-19 14:09 UTC, Fajfa commented on client/web/admin/src/views/System/Cdns/Index.vue
> +        .then(settings => {
settings[0] could throw an error, make sure that's handled

2024-08-19 14:09 UTC, Fajfa commented on client/web/admin/src/views/System/Cdns/Index.vue
> +          if (action === 'delete') {
This can be a bit cleaner. You repeat the same line in both ifs.

2024-08-19 14:09 UTC, Fajfa commented on client/web/admin/src/views/System/Cdns/Index.vue
> +        class="mb-0"
Some min height is necessary.

2024-08-21 12:35 UTC, closed without merging