Add record from record selector field
cortezaproject/corteza pull request #1894
Opened 2024-08-28 06:42 UTC by katrinDY

# The following changes are implemented
TODO: Summary

# Changes in the user interface:
TODO: Add screenshots, recordings or remove this section

# Checklist when submitting a final (!draft) PR
 - [ ] Commits are tidied up, squashed if needed and follow guidelines in CONTRIBUTING.md
 - [ ] Code builds
 - [ ] All existing tests pass
 - [ ] All new critical code is covered by tests
 - [ ] PR is linked to the relevant issue(s)
 - [ ] Rebased with the target branch

2024-08-28 11:07 UTC, Fajfa requested changes

2024-08-28 11:07 UTC, Fajfa commented on client/web/compose/src/components/ModuleFields/Editor/Record.vue
> +      const { page } = this.getRecordSelectorPage()
You need to show the button only if record can be added for that module (same as record list +Add button check)

That means if recordPage exists and user can creat a record for that module

2024-08-28 11:07 UTC, Fajfa commented on client/web/compose/src/components/ModuleFields/Editor/Record.vue
> +      const { page } = this.getRecordSelectorPage()
page can be undefined here which then breaks this

2024-08-28 11:07 UTC, Fajfa commented on locale/en/corteza-webapp-compose/block.yaml
> +  recordSelectorAddRecordDisplayOption: Add record via selector field
On selector record create
While you're here can you also rename the On record selector click to On record value click

2024-08-28 11:07 UTC, Fajfa commented on locale/en/corteza-webapp-compose/block.yaml
> +  add: Users will be able to add new records
Can create records via selector

2024-08-28 11:07 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/RecordConfigurator.vue
> +        .find(f => f.kind === 'Record' && (f.options.labelField || f.options.recordLabelField))
i think just kind is ok, since it might confuse people if they don't see it. 
Also use some instead of find so it returns a boolean

2024-08-28 11:07 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/RecordConfigurator.vue
> +
Can you also add the "recordSelectorDisplayOptions and referenceField" under this template please

2024-08-28 11:07 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/RecordEditor.vue
> +    refreshOnRelatedRecordsUpdate ({ moduleID, notPageID }) {
I think we misunderstood each other, I said to add this to the record editor field, and refresh its options when this event is called.
We don't refresh record editor block so that users don't lose their changes.

2024-08-28 11:07 UTC, Fajfa commented on lib/js/src/compose/types/page-block/record.ts
> +  showAddRecordButton: boolean;
since others are prefixed with record selectors lets do the same for this one
`recordSelectorShowAddRecordButton`

2024-08-30 12:43 UTC, katrinDY commented on client/web/compose/src/components/PageBlocks/RecordEditor.vue
> +    refreshOnRelatedRecordsUpdate ({ moduleID, notPageID }) {
Sorry, my bad

2024-08-30 14:19 UTC, merged