Forbid password reuse
cortezaproject/corteza pull request #377
Opened 2022-07-01 14:38 UTC by petergrlica

When:
 - change password in admin
 - change password on auth
 - reset password via email

2022-07-01 14:46 UTC, darh requested changes

2022-07-01 14:46 UTC, darh commented on system/service/auth.go
> +		if svc.CheckPassword(password, true, cc) {
can you explain here why we do 2 calls

2022-07-01 14:46 UTC, darh commented on system/types/credentials.go
>  // CompareHashAndPassword returns first valid credentials with matching hash
with introduction of the validOnly the description of the function is no longer correct

2022-07-01 14:46 UTC, darh commented on system/service/user.go
> +		cc, _, err = store.SearchCredentials(ctx, svc.store, types.CredentialsFilter{
this block of code is repeated 3 times, it should be moved into a utility func

2022-07-14 10:54 UTC, tjerman commented on system/service/auth_credentials.go
> +// loadFromTokenAndConfirmEmail loads token, confirms user's
... confirms user's email

2022-07-14 10:54 UTC, tjerman commented on system/service/auth_credentials.go
> +}
Worth considering defining a `type CredentialsSet []*types.Credentials` and having this there

2022-07-14 10:54 UTC, tjerman commented on system/service/auth.go
> +	if c != nil {
can `c` ever be `nil`? I'd imagine proc login should never happen if there is no `c`

2022-07-14 10:54 UTC, tjerman commented on system/service/auth_credentials.go
> +	credentialsTypeMFAEmailOTP                 = "mfa-email-otp"
Should we enum these?

2022-07-14 10:54 UTC, tjerman commented on system/service/auth_credentials.go
> +		}
Worth considering having another event here; `on userEmailConfirmed` for things like welcome or success email notifications, lead -> customer conversion, ...

2022-07-14 10:54 UTC, tjerman commented on system/service/auth_credentials.go
> +func (svc *auth) loadFromTokenAndConfirmEmail(ctx context.Context, token, tokenType string) (u *types.User, err error) {
Should the action log logging happen in the parent function instead of here?

2022-07-14 10:54 UTC, tjerman commented on system/service/auth_credentials.go
> +	return u, svc.store.Tx(ctx, func(ctx context.Context, s store.Storer) (err error) {
I think we usually use `store.Tx` instead of the direct receiver fnc

2022-07-14 10:54 UTC, tjerman commented on system/service/auth_credentials.go
> +		}
I'd move this to some function to make the current one a bit shorter

2022-07-14 10:54 UTC, tjerman commented on system/service/auth_credentials.go
> +		// and enforces one-token-per-user rule
This should be the comment for the function definition

2022-07-14 10:54 UTC, tjerman commented on system/service/auth_credentials.go
> +		}
I'd use `if kind != ...` just to make it shorter

2022-07-14 10:54 UTC, tjerman commented on system/service/auth_credentials.go
> +func (svc *auth) cleanupCredentials(ctx context.Context, s store.Credentials, cc types.CredentialsSet) (err error) {
Won't this delete old user passwords making the password reuse check not possible?

2022-07-14 10:54 UTC, tjerman commented on system/service/auth_credentials.go
> +		}
This doesn't need to happen; if the password was previously ok and the code below matches to it, this bit doesn't matter

2022-07-14 10:54 UTC, tjerman commented on system/service/auth_credentials.go
> +func (svc *auth) CheckPasswordStrength(password string) bool {
Should we move the `len(password) == 0` check to here and remove it elsewhere?

2022-07-14 10:54 UTC, tjerman commented on system/service/auth_credentials.go
> +//}
Delete

2022-07-14 10:54 UTC, tjerman commented on system/service/auth_credentials.go
> +	if len(cc) > 0 && svc.settings.Auth.Internal.Enabled {
you can move the `svc.settings.Auth.Internal.Enabled` bit to the top and avoid needless computation in case it is not enabled

2022-07-14 10:54 UTC, tjerman commented on system/service/auth_credentials.go
> +}
remove

2022-07-14 18:25 UTC, darh commented on system/service/auth_credentials.go
> +}
we have it, I chose not to use it.... no spec. reason.

2022-07-14 18:32 UTC, darh commented on system/service/auth.go
> +	if c != nil {
You are correct but I remember some nil pointer errors that this might have addressed. 
I've moved the checks (+ errors) at the top of the fn

2022-07-14 18:32 UTC, darh commented on system/service/auth_credentials.go
> +		}
yap.

2022-07-14 18:53 UTC, darh commented on system/service/auth_credentials.go
> +func (svc *auth) CheckPasswordStrength(password string) bool {
nope, might break old pre-pwd-strength-policy passwords.

2022-07-14 18:53 UTC, darh commented on system/service/auth_credentials.go
> +		}
how could empty password ever be ok?

2022-07-14 18:54 UTC, darh commented on system/service/auth_credentials.go
> +	credentialsTypeMFAEmailOTP                 = "mfa-email-otp"
not for now.

2022-07-17 11:24 UTC, closed without merging