2023.3.x feature magnify page blocks
cortezaproject/corteza pull request #576
Opened 2022-11-25 16:22 UTC by yonkov

# The following changes are implemented

Integrators can configure certain block types to allow magnification, showing the content of the block inside a modal window or in fullscreen mode.

# Changes in the user interface:

![image](https://user-images.githubusercontent.com/26258032/204024287-ec97c725-8ae3-4319-8139-eaee1ab22277.png)

![image](https://user-images.githubusercontent.com/26258032/204024202-fb3f6fda-2753-4a7d-a4d1-aae596bc9b6d.png)

2022-11-29 11:01 UTC, Fajfa requested changes

2022-11-29 11:01 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/Configurator.vue
> +        { value: 'disabled', text: this.$t('general.magnifyOptions.disabled') },
Change the value of this to '' and you can have an easier time in the other conditions.

2022-11-29 11:01 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/Wrap/Card.vue
> +      return this.block.options.magnifyOption ? !(this.block.options.magnifyOption === 'disabled') : false
For example this can be a much nicer condition if your "disabled" value is ''. Think about it a bit

You should also hide this if the block is already magnified

2022-11-29 11:01 UTC, Fajfa commented on client/web/compose/src/components/Public/Page/Modal.vue
> +<template>
Wouldn't this be located in `/Public/Page/Block` ?
Since its magnifying a block not the page

2022-11-29 11:01 UTC, Fajfa commented on client/web/compose/src/components/Public/Page/Modal.vue
> +        this.modalClass = this.block.options.magnifyOption
modal class should be a computed property, since you already are saving the block

2022-11-29 11:01 UTC, Fajfa commented on client/web/compose/src/components/Public/Page/Modal.vue
> +        this.blockID = blockID
Why save blockID separately? All you need is the block

2022-11-29 11:01 UTC, Fajfa commented on client/web/compose/src/components/Public/Page/Modal.vue
> +    :id="modalClass === 'fullscreen' ? 'page-block-fullwidth-modal' : 'page-block-modal'"
No need for id please. Use the :class to achieve this. Return it with the modalClass computed property

2022-11-29 11:01 UTC, Fajfa commented on client/web/compose/src/components/Public/Page/Modal.vue
> +    <template #modal-footer>
Why do we need a footer here?

2022-11-29 11:01 UTC, Fajfa commented on client/web/compose/src/components/Public/Page/Modal.vue
> +    <template
This template doesn't do anything

2022-11-29 11:01 UTC, Fajfa commented on client/web/compose/src/components/Public/Page/Modal.vue
> +          query: { blockID: this.blockID },
Why use this.blockID when you can just use blockID

2022-11-29 11:01 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/Wrap/Card.vue
> +        @click="handleModalOpen"
More fitting name please (openBlockInModal) for example.
Or something even better

2022-11-29 11:01 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/Wrap/Card.vue
> +      </b-button>
How about that empty line

2022-11-29 11:01 UTC, Fajfa commented on client/web/compose/src/components/Public/Page/Modal.vue
> +        :bounding-rect="boundingRect"
Do you need this?

2022-11-29 11:01 UTC, Fajfa commented on lib/js/src/compose/types/page-block/base.ts
> +  public options = { }
no need for extra space between {}

2022-11-29 11:01 UTC, Fajfa commented on client/web/compose/src/components/Public/Page/Modal.vue
> +  #page-block-modal .modal-dialog {
So both should be height 100% right? Only the max width should change with class

Also fullscreen means fullscreen!

2022-11-29 11:01 UTC, Fajfa commented on lib/js/src/compose/types/page-block/calendar/page-block.ts
> +  public magnifyOption = 'disabled'
'' should be the default

2022-11-29 15:28 UTC, yonkov commented on client/web/compose/src/components/Public/Page/Modal.vue
> +    :id="modalClass === 'fullscreen' ? 'page-block-fullwidth-modal' : 'page-block-modal'"
I do not think you can use `:class` prop on a b-modal. I tried but it did not work.

2022-11-29 16:10 UTC, yonkov commented on client/web/compose/src/components/Public/Page/Modal.vue
> +        :bounding-rect="boundingRect"
If I remove this, I get `[Vue warn]: Error in render: "Error: block prop missing"`

2022-12-02 14:44 UTC, Fajfa requested changes

2022-12-02 14:44 UTC, Fajfa commented on client/web/compose/src/components/Public/Page/Block/Modal.vue
> +    modalClass () {
Instead of having this computed, have computed for the dialog and content class

2022-12-02 14:44 UTC, Fajfa commented on client/web/compose/src/components/Public/Page/Block/Modal.vue
> +      this.$router.replace({ query: { } })
The extra space inside the {} is not needed

2022-12-02 14:44 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/Wrap/Plain.vue
> +      <b-button
Look at line 43 in the same file and do it like that please, since its pretty much the same kind of function.

And same in plain

2022-12-08 15:30 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/Configurator.vue
> +      const disabledOption = this.block.options.magnifyOption === NoID ? NoID: '';
No need for this no?

2022-12-08 15:32 UTC, Fajfa commented on client/web/compose/src/components/Public/Page/Block/Modal.vue
> +        this.showBlockModal = false
I think we can safely put this into hideModal

2022-12-08 15:36 UTC, Fajfa commented on client/web/compose/src/components/PageBlocks/Wrap/Card.vue
> +      return this.block.id = this.$route.query.blockID
isnt it this.block.blockID? Same for Plain

2022-12-12 10:33 UTC, merged