Add support for page icon
cortezaproject/corteza pull request #881
Opened 2023-02-18 10:31 UTC by vicpatel

- [ ] Allow integrators to upload an icon for the sidebar
 - [ ] Allow integrators to select one of the previously uploaded icons for the sidebar
 - [ ] Allow integrators to select icons from the library of the sidebar
 - [ ] Allow integrators to explicitly select pages that expand

# Changes in the user interface:
TODO: Add screenshots, recordings or remove this section

# Checklist when submitting a final (!draft) PR
 - [ ] Commits are tidied up, squashed if needed and follow guidelines in CONTRIBUTING.md
 - [ ] Code builds
 - [ ] All existing tests pass
 - [ ] All new critical code is covered by tests
 - [ ] PR is linked to the relevant issue(s)
 - [ ] Rebased with the target branch

2023-03-16 11:41 UTC, tjerman commented on server/compose/rest.yaml
> +          parser: label.ParseStrings
Let's not use a label parser here. The code will probably be the same but still

2023-03-16 11:41 UTC, tjerman commented on server/compose/rest/pageIcon.go
Would this be better generalized instead of page specific? There might be some upcoming features which would add icons to module fields also.

I see you're using the original attachment service so I don't think it'd be much of an issue if you do decide to leave it as is. My original thought was that this feature would present a little _icon gallery_ which you could use all over the place.

2023-03-16 11:41 UTC, tjerman commented on server/compose/service/attachment.go
> +		// add helper for below code block
Remenent of copilot?

2023-03-16 11:41 UTC, tjerman commented on server/compose/types/pageIcon.go
Do we really need to present page icons like so? Perhaps it should be more like regular attachments.

2023-03-20 14:42 UTC, Fajfa requested changes

2023-03-20 14:42 UTC, Fajfa commented on client/web/admin/src/components/Settings/Compose/CComposeEditorBasic.vue
> +        </b-input-group>
No need for input groups where there is no need for input groups

2023-03-20 14:42 UTC, Fajfa commented on lib/js/src/shared/types/attachment.ts
>    public meta: Meta = {};
You dont need these attachment changes

2023-03-20 14:42 UTC, Fajfa commented on lib/vue/src/components/filePreview/CPreviewInline.vue
> +        :disabled="disabled"
You dont need this file

2023-03-20 14:42 UTC, Fajfa commented on lib/vue/src/components/filePreview/common/base.vue
> +    },
You dont need this file

2023-03-20 14:42 UTC, Fajfa commented on lib/vue/src/components/filePreview/common/types/IMG/InlineIMG.vue
> +  <div
You dont need this file

2023-03-20 14:42 UTC, Fajfa commented on client/web/compose/src/components/Public/Page/Attachment/ListLoader.vue
> +      class="single gallery px-2"
You dont need this

2023-03-23 07:51 UTC, merged